### ISSUE TITLE
Public sass version to npm as well

### ISSUE THREAD

**Issue by RickEyre** [webdesignberlin/css-reset-and-normalize-sass#1]
If I `npm install` only the CSS comes along.

**Comment by simbo** [comment]
Because the properties `files` and `main` in package.json still have the values from the original stylus version, from which it was copied.

btw: issues tracker url in package.json also has the name of the original repo

**Comment by webdesignberlin** [comment]
thank you for the notes @RickEyre , @simbo . Its fixed in [v0.1.1](b9bd11a2a0b3e37c5d1370ccbab6fc8be50587ba)
