### ISSUE TITLE
$with-flavor variable not defined

### ISSUE THREAD

**Issue by roryprimrose** [webdesignberlin/css-reset-and-normalize-sass#2]
I'm running this following in gulp:

```
var paths = {
    webroot: "./",
    bower: "./bower_components/",
    contentTarget: "./content/",
};

var find = {
    styles: [
        paths.bower + "css-reset-and-normalize-sass/scss/reset-and-normalize.scss"
    ],
}

gulp.task("styles", ["cleanStyles"], function() {
    return gulp.src(find.styles)
        .pipe(plumberNotifier())
        .pipe(sourcemaps.init())
        .pipe(sass({outputStyle: 'compressed'}))
        .pipe(concat("app.css", { newLine: "\r\n" }))
        .pipe(sourcemaps.write(paths.webroot))
        .pipe(gulp.dest(paths.contentTarget));
});
```

This gives me the following error:

```
[13:38:42] Starting 'cleanStyles'...
[13:38:42] Finished 'cleanStyles' after 15 ms
[13:38:42] Starting 'styles'...
[13:38:42] Error in plugins **gulp-sass**:bower_components\css-reset-and-normalize-sass\scss\imports\_normalize.scss
Error: Undefined variable: "$with-flavor".
        on line 23 of bower_components/css-reset-and-normalize-sass/scss/imports/_normalize.scss
>>   @if ($with-flavor) {
   -------^
[13:38:42] Finished 'styles' after 35 ms
```

I've been researching to find out why the check around the variable existing does not work but so far I'm not getting anywhere. My workaround is the following:

Remove the following variable exists check from the top of _normalize.scss

```
// set var if not present
@if variable-exists(with-flavor) {

} @else {
  $with-flavor: false;
}
```

Change reset-and-normalize.scss to

```
$with-flavor: false;

@import 'imports/reset';

@import 'imports/normalize';
```

Change flavored-reset-and-normalize.scss to

```
$with-flavor: true;

@import 'imports/reset';

@import 'imports/normalize';

@import 'imports/flavor';
```

This takes away the reuse of reset-and-normalize.scss but this was providing minimal benefit anyway. This now compiles with both top level scss files.

I haven't raised a pull request just in-case I am missing something obvious.

**Comment by simbo** [comment]
A better way would be using the `!default` operator to produce the same behavior like in the original stylus version (where the equivalent `?=` operator is used).

In `_normalize.scss` replace the `@if` with

``` scss
$with-flavor: false !default;
```

This way you keep your necessary variable definitions within the modules which require them and don't pollute other files.

The `!default` operator should also be used when setting `$with-flavor` in `flavored-reset-and-normalize.scss`. This way we allow the user to include that file and still take control over using flavored version or not.

**Comment by webdesignberlin** [comment]
Thanks for the report. I have the same opinion as simbo. according to the code is adapted. thank you.
